services:
  - type: web
    name: chat-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: chat-app-redis
          property: connectionString

  - type: redis
    name: chat-app-redis
    ipAllowList: []
    plan: free

databases:
  - name: chat-app-db
    databaseName: chat_app_production
    plan: free
