# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Create database directories
        run: |
          mkdir -p db
          mkdir -p tmp

      - name: Setup test database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test

      - name: Run Ruby tests
        run: bundle exec rake

      - name: Upload Ruby test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/.resultset.json
          flags: ruby
          fail_ci_if_error: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm install

      - name: Run JavaScript tests with coverage
        run: npm run test:coverage

      - name: Upload JavaScript test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/jest/lcov.info
          flags: javascript
          fail_ci_if_error: false
